ALTER TABLE "User" ADD COLUMN "activationPlan" TEXT NOT NULL DEFAULT 'permanent';
ALTER TABLE "User" ADD COLUMN "activationStartsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN "activationEndsAt" TIMESTAMP(3);
